"""
ZipBuilder — Creates in-memory ZIP archives for generated websites.

Produces a Vercel-compatible Vite project structure so the user can download,
unzip, ``npm install && npm run dev``, and deploy directly to Vercel.
"""

from __future__ import annotations

import io
import zipfile
from datetime import datetime


class ZipBuilder:
    """Builds downloadable ZIP archives from a generated file map."""

    # ------------------------------------------------------------------
    # Boilerplate files injected into every ZIP
    # ------------------------------------------------------------------

    _VERCEL_JSON = """{
  "framework": "vite",
  "buildCommand": "npm run build",
  "outputDirectory": "dist",
  "installCommand": "npm install"
}
"""

    _GITIGNORE = """node_modules
dist
.env
.env.local
*.log
.DS_Store
"""

    @staticmethod
    def _readme(project_name: str) -> str:
        return f"""# {project_name}

> Portfolio website generated by **Resume Gala** ✨

## Quick Start

```bash
# Install dependencies
npm install

# Start development server
npm run dev

# Build for production
npm run build
```

## Deploy to Vercel

1. Push this folder to a GitHub repository.
2. Import the repository on [vercel.com/new](https://vercel.com/new).
3. Vercel will auto-detect the Vite framework — just click **Deploy**.

---

*Generated on {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}*
"""

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @staticmethod
    def build_zip(files: dict[str, str], project_name: str = "resume-gala-site") -> bytes:
        """Create a ZIP archive from a filename→code mapping.

        Parameters
        ----------
        files:
            Mapping of relative file paths (e.g. ``src/App.jsx``) to source
            code strings.
        project_name:
            Name used for the root directory inside the ZIP and the README
            heading.

        Returns
        -------
        bytes
            The raw ZIP file content, ready to be returned as a download.
        """

        buf = io.BytesIO()

        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
            root = project_name

            # --- user-generated files ---
            for path, content in files.items():
                # Normalise path separators and strip leading slashes / dots
                clean = path.lstrip("./\\")
                zf.writestr(f"{root}/{clean}", content)

            # --- boilerplate ---
            zf.writestr(f"{root}/vercel.json", ZipBuilder._VERCEL_JSON)
            zf.writestr(f"{root}/.gitignore", ZipBuilder._GITIGNORE)
            zf.writestr(f"{root}/README.md", ZipBuilder._readme(project_name))

        return buf.getvalue()
