'use client';

import { useState, useCallback, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import ResumeForm from '@/components/ResumeForm';
import PromptInput from '@/components/PromptInput';
import GenerationStatus from '@/components/GenerationStatus';
import SandpackPreview from '@/components/SandpackPreview';
import ChatEditor from '@/components/ChatEditor';
import { Wand2, ArrowLeft, Loader2, Save, Check } from 'lucide-react';
import { savePortfolio, getPortfolio } from '@/lib/portfolioApi';

const SAMPLE_FILES = {
  '/App.js': `import React from 'react';

export default function App() {
  return (
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
      color: 'white',
      fontFamily: "'Inter', sans-serif",
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '2rem',
    }}>
      <h1 style={{ fontSize: '3rem', marginBottom: '1rem' }}>
        🎉 Your Portfolio
      </h1>
      <p style={{ fontSize: '1.2rem', opacity: 0.8 }}>
        Generated by Resume Gala
      </p>
    </div>
  );
}`,
};

const STORAGE_KEY = 'resume-gala:generate-state:v1';
const CLEAR_DRAFT_KEY = 'resume-gala:generate-clear-draft:v1';

function safeParse(json, fallback) {
  try {
    return JSON.parse(json);
  } catch {
    return fallback;
  }
}

export default function GeneratePage() {
  const searchParams = useSearchParams();
  const [step, setStep] = useState('input');
  const [formData, setFormData] = useState({
    personal: { name: '', title: '', social: { github: '', linkedin: '' } },
    education: [],
    experience: [],
    skills: [],
    projects: [],
  });
  const [prompt, setPrompt] = useState('');
  const [jobId, setJobId] = useState(null);
  const [files, setFiles] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [portfolioId, setPortfolioId] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [saveStatus, setSaveStatus] = useState('idle'); // 'idle' | 'saving' | 'saved' | 'error'

  // Align with lib/portfolioApi defaults (127.0.0.1 is more reliable than localhost)
  const RAW_API_URL = process.env.NEXT_PUBLIC_API_URL;
  const apiUrl = RAW_API_URL === '' ? '' : (RAW_API_URL || 'http://127.0.0.1:8000');

  // Poll generation status when we have a jobId and are in generating state
  useEffect(() => {
    if (!jobId || step !== 'generating') return;

    let cancelled = false;
    let timer = null;

    const poll = async () => {
      try {
        const res = await fetch(`${apiUrl}/api/generate/status/${jobId}`);
        if (!res.ok) throw new Error('Failed to fetch generation status');
        const data = await res.json();
        if (cancelled) return;

        if (data.status === 'completed') {
          if (data.files && Object.keys(data.files).length > 0) {
            setFiles(data.files);
            if (data.preview_url) {
              setPreviewUrl(data.preview_url);
            }
            setStep('preview');

            // Auto-save immediately in local-only mode.
            (async () => {
              try {
                setSaveStatus('saving');
                const saved = await savePortfolio({
                  title: formData?.personal?.name
                    ? `${formData.personal.name}'s Portfolio`
                    : 'Untitled Portfolio',
                  prompt,
                  resumeData: formData,
                  files: data.files,
                  jobId,
                });
                setPortfolioId(saved.id);
                setSaveStatus('saved');
                setTimeout(() => setSaveStatus('idle'), 3000);
              } catch (err) {
                console.error('Auto-save failed:', err);
                setSaveStatus('error');
              }
            })();
          } else {
            console.error('Job completed but no files returned');
            setStep('input');
            alert('Generation completed but no files were returned. Please try again.');
          }
          return;
        }

        if (data.status === 'failed') {
          console.error('Generation failed:', data.error);
          setStep('input');
          alert(`Generation failed: ${data.error || 'Unknown error'}`);
          return;
        }

        // still running/pending
        timer = setTimeout(poll, 1500);
      } catch (err) {
        // Most common cause is backend not running / wrong API URL.
        console.error('Status poll error:', err);
        timer = setTimeout(poll, 2000);
      }
    };

    poll();

    return () => {
      cancelled = true;
      if (timer) clearTimeout(timer);
    };
  }, [jobId, step, apiUrl, formData, prompt]);

  // Restore state after refresh/restart
  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(STORAGE_KEY);
      if (!raw) return;
      const saved = safeParse(raw, null);
      if (!saved) return;

      if (saved.formData) setFormData(saved.formData);
      if (typeof saved.prompt === 'string') setPrompt(saved.prompt);
      if (saved.jobId) setJobId(saved.jobId);
      if (saved.files) setFiles(saved.files);
      if (saved.step) setStep(saved.step);
    } catch {
      // ignore
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Persist state so users don't lose work
  useEffect(() => {
    try {
      const payload = {
        step,
        formData,
        prompt,
        jobId,
        files,
        updatedAt: Date.now(),
      };
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(payload));
    } catch {
      // ignore quota / serialization issues
    }
  }, [step, formData, prompt, jobId, files]);

  // Load portfolio from URL param if present (local-only)
  useEffect(() => {
    const id = searchParams.get('id');
    if (!id) return;

    let cancelled = false;
    (async () => {
      try {
        const portfolio = await getPortfolio(id);
        if (cancelled) return;
        setPortfolioId(portfolio.id);
        if (portfolio.files) setFiles(portfolio.files);
        if (portfolio.resume_data) setFormData(portfolio.resume_data);
        if (portfolio.prompt) setPrompt(portfolio.prompt);
        setJobId(portfolio.job_id || null);
        setStep('preview');
      } catch (err) {
        console.error('Failed to load portfolio:', err);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [searchParams]);

  // Auto-save when generation completes (local-only: always save)
  const handleAutoSave = useCallback(
    async (generatedFiles, currentJobId) => {
      try {
        setSaveStatus('saving');
        const saved = await savePortfolio({
          title: formData?.personal?.name
            ? `${formData.personal.name}'s Portfolio`
            : 'Untitled Portfolio',
          prompt,
          resumeData: formData,
          files: generatedFiles,
          jobId: currentJobId,
        });
        setPortfolioId(saved.id);
        setSaveStatus('saved');
        setTimeout(() => setSaveStatus('idle'), 3000);
      } catch (err) {
        console.error('Auto-save failed:', err);
        setSaveStatus('error');
      }
    },
    [formData, prompt]
  );

  const handleManualSave = async () => {
    if (!files || saveStatus === 'saving') return;
    try {
      setSaveStatus('saving');
      const saved = await savePortfolio({
        title: formData?.personal?.name
          ? `${formData.personal.name}'s Portfolio`
          : 'Untitled Portfolio',
        prompt,
        resumeData: formData,
        files,
        jobId,
      });
      setPortfolioId(saved.id);
      setSaveStatus('saved');
      setTimeout(() => setSaveStatus('idle'), 3000);
    } catch (err) {
      console.error('Save failed:', err);
      setSaveStatus('error');
    }
  };

  const hasResumeData = () => {
    const personal = formData?.personal || {};
    if ((personal.name || '').trim() || (personal.title || '').trim()) return true;
    if ((formData?.education || []).length > 0) return true;
    if ((formData?.experience || []).length > 0) return true;
    if ((formData?.skills || []).length > 0) return true;
    if ((formData?.projects || []).length > 0) return true;
    return false;
  };

  const handleSubmit = async () => {
    if (submitting) return;
    if (!hasResumeData()) {
      alert('Please fill or upload your resume data before generating.');
      return;
    }
    setSubmitting(true);

    try {
      const res = await fetch(`${apiUrl}/api/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          resume_input: formData,
          user_prompt: prompt,
          github_url: formData?.personal?.social?.github || null,
          linkedin_url: formData?.personal?.social?.linkedin || null,
        }),
      });

      if (!res.ok) throw new Error('Generation request failed');

      const data = await res.json();

      if (data.files) {
        // Direct response with files
        setFiles(data.files);
        setJobId(data.job_id || 'direct');
        setStep('preview');
        handleAutoSave(data.files, data.job_id || 'direct');
      } else if (data.job_id) {
        // Async generation
        setJobId(data.job_id);
        setStep('generating');
      }
    } catch (err) {
      console.error('Submit error:', err);
      // For demo purposes, show sample preview
      setFiles(SAMPLE_FILES);
      setJobId('demo');
      setStep('preview');
      // Don't auto-save demo data
    } finally {
      setSubmitting(false);
    }
  };

  const handleGenerationComplete = useCallback((generatedFiles) => {
    setFiles(generatedFiles);
    setStep('preview');
    handleAutoSave(generatedFiles, jobId);
  }, [handleAutoSave, jobId]);

  const handleFilesUpdate = useCallback((updatedFiles) => {
    setFiles(updatedFiles);
  }, []);

  const handleReset = () => {
    // Reset UI, but keep draft persisted so Back/Refresh doesn't wipe work.
    setStep('input');
    setFiles(null);
    setJobId(null);
    setPreviewUrl(null);
  };

  const handleClearDraft = () => {
    setStep('input');
    setFiles(null);
    setJobId(null);
    setPrompt('');
    setFormData({
      personal: { name: '', title: '', social: { github: '', linkedin: '' } },
      education: [],
      experience: [],
      skills: [],
      projects: [],
    });
    setPortfolioId(null);
    setPreviewUrl(null);
    try {
      window.localStorage.removeItem(STORAGE_KEY);
      window.localStorage.setItem(CLEAR_DRAFT_KEY, String(Date.now()));
    } catch {
      // ignore
    }
  };

  return (
    <div className="container-wide" style={{ padding: 'var(--space-xl) var(--space-lg)' }}>
      <AnimatePresence mode="wait">
        {/* INPUT STEP */}
        {step === 'input' && (
          <motion.div
            key="input"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.4 }}
          >
            {/* Page header */}
            <div style={{ textAlign: 'center', marginBottom: 'var(--space-2xl)' }}>
              <h1
                style={{
                  fontSize: '2rem',
                  fontWeight: 700,
                  marginBottom: 'var(--space-sm)',
                  letterSpacing: '-0.02em',
                }}
              >
                Generate Your{' '}
                <span className="gradient-text">Portfolio</span>
              </h1>
              <p style={{ color: 'var(--text-secondary)', fontSize: '1rem' }}>
                Fill in your resume details and describe your ideal style
              </p>
            </div>

            {/* Two column layout */}
            <div className="generate-layout">
              <div className="generate-panel">
                <ResumeForm value={formData} onChange={setFormData} apiUrl={apiUrl} />
              </div>
              <div className="generate-panel">
                <PromptInput value={prompt} onChange={setPrompt} />

                {/* Quick info card */}
                <div
                  className="card-static"
                  style={{
                    padding: 'var(--space-lg)',
                    background: 'var(--gradient-subtle)',
                    borderColor: 'rgba(139, 92, 246, 0.15)',
                  }}
                >
                  <h4
                    style={{
                      fontSize: '0.9rem',
                      fontWeight: 600,
                      marginBottom: 'var(--space-sm)',
                      color: 'var(--accent-purple-light)',
                    }}
                  >
                    💡 Tips for best results
                  </h4>
                  <ul
                    style={{
                      fontSize: '0.85rem',
                      color: 'var(--text-secondary)',
                      lineHeight: 1.8,
                      paddingLeft: 'var(--space-md)',
                    }}
                  >
                    <li style={{ listStyleType: 'disc' }}>
                      Fill in at least your name and title
                    </li>
                    <li style={{ listStyleType: 'disc' }}>
                      Add 2-3 skills for better personalization
                    </li>
                    <li style={{ listStyleType: 'disc' }}>
                      Be descriptive in your style prompt
                    </li>
                    <li style={{ listStyleType: 'disc' }}>
                      You can always edit after generation
                    </li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Submit button */}
            <div className="generate-submit">
              <button
                className="btn-primary"
                onClick={handleSubmit}
                disabled={submitting}
                style={{
                  fontSize: '1.05rem',
                  padding: '16px 40px',
                }}
              >
                {submitting ? (
                  <>
                    <Loader2 size={20} style={{ animation: 'spin 1s linear infinite' }} />
                    Sending to AI...
                  </>
                ) : (
                  <>
                    <Wand2 size={20} />
                    Generate Website
                  </>
                )}
              </button>
            </div>
          </motion.div>
        )}

        {/* GENERATING STEP */}
        {step === 'generating' && (
          <motion.div
            key="generating"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.4 }}
            style={{ maxWidth: 800, margin: '0 auto' }}
          >
            <GenerationStatus
              jobId={jobId}
              onComplete={handleGenerationComplete}
            />
          </motion.div>
        )}

        {/* PREVIEW STEP */}
        {step === 'preview' && (
          <motion.div
            key="preview"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.4 }}
          >
            {/* Header with back button */}
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                marginBottom: 'var(--space-xl)',
              }}
            >
              <div>
                <h2
                  style={{
                    fontSize: '1.5rem',
                    fontWeight: 700,
                    marginBottom: 'var(--space-xs)',
                  }}
                >
                  ✨ Your Portfolio is Ready
                </h2>
                <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>
                  Preview your generated website and make edits below
                </p>
              </div>
              <div style={{ display: 'flex', gap: 'var(--space-sm)' }}>
                <button
                  className="btn-secondary"
                  onClick={handleManualSave}
                  disabled={saveStatus === 'saving'}
                  style={{
                    color: saveStatus === 'saved' ? 'var(--accent-green)' : undefined,
                  }}
                >
                  {saveStatus === 'saving' ? (
                    <>
                      <Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} /> Saving...
                    </>
                  ) : saveStatus === 'saved' ? (
                    <>
                      <Check size={16} /> Saved!
                    </>
                  ) : (
                    <>
                      <Save size={16} /> Save
                    </>
                  )}
                </button>
                <button className="btn-secondary" onClick={handleReset}>
                  <ArrowLeft size={16} />
                  Start Over
                </button>
                <button
                  className="btn-secondary"
                  onClick={() => {
                    if (confirm('Clear the saved draft state? This cannot be undone.')) {
                      handleClearDraft();
                    }
                  }}
                  style={{ color: 'var(--accent-red, #ef4444)' }}
                >
                  Clear Draft
                </button>
              </div>
            </div>

            {/* Preview */}
            <div style={{ marginBottom: 'var(--space-xl)' }}>
              <SandpackPreview files={files} jobId={jobId} previewUrl={previewUrl} />
            </div>

            {/* Chat Editor */}
            <div>
              <h3
                style={{
                  fontSize: '1.1rem',
                  fontWeight: 600,
                  marginBottom: 'var(--space-md)',
                }}
              >
                ✏️ Edit with AI
              </h3>
              <ChatEditor files={files} onFilesUpdate={handleFilesUpdate} />
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
